# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # We only test only a subset of os & r combination for non CRAN packages
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: https://Pandora-IsoMemo.github.io/drat/

      - name: Install JAGS on macOS
        if: matrix.config.os == 'macos-latest'
        run: brew install jags

      - name: Install JAGS on Windows
        if: matrix.config.os == 'windows-latest'
        run: |
          $retryCount = 3
          for ($i = 0; $i -lt $retryCount; $i++) {
            try {
              Invoke-WebRequest -Uri "http://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/4.3.0/JAGS-4.3.0.exe/download" -OutFile "jags-installer.exe"
              if (Test-Path -Path "jags-installer.exe") {
              Write-Output "Downloaded JAGS installer successfully."
              break
            }
          } catch {
            Write-Output "Download attempt $($i + 1) failed. Retrying..."
            if ($i -eq ($retryCount - 1)) {
              throw "Failed to download JAGS installer after $retryCount attempts."
            }
            Start-Sleep -Seconds 5
          }
        }
        Start-Process -Wait -FilePath jags-installer.exe -ArgumentList "/S"
        echo "C:\\Program Files\\JAGS\\JAGS-4.3.0\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
